# Copyright 2020 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

import("../../../testing/test.gni")
import("../../Lynx.gni")
import("build.gni")

if (enable_cssjit) {
  config("asmjit_config") {
    include_dirs = [ "//third_party/asmjit" ]
    if (is_mac) {
      cflags_cc = [ "-Wno-unguarded-availability-new" ]
    }
    defines = [
      "ASMJIT_STATIC=1",
      "ASMJIT_NO_UJIT=1",
      "ASMJIT_NO_FOREIGN=1",
      "ASMJIT_NO_COMPILER=1",
      "ASMJIT_NO_ABI_NAMESPACE=1",

      # comment following macros for diagnosis
      "ASMJIT_NO_LOGGING=1",
      "ASMJIT_NO_INTROSPECTION=1",
      "ASMJIT_NO_TEXT=1",
    ]
  }
  source_set("asmjit") {
    public_configs = [ ":asmjit_config" ]
    sources = [
      "//third_party/asmjit/asmjit/arm/a64assembler.cpp",
      "//third_party/asmjit/asmjit/arm/a64builder.cpp",
      "//third_party/asmjit/asmjit/arm/a64compiler.cpp",
      "//third_party/asmjit/asmjit/arm/a64emithelper.cpp",
      "//third_party/asmjit/asmjit/arm/a64formatter.cpp",
      "//third_party/asmjit/asmjit/arm/a64func.cpp",
      "//third_party/asmjit/asmjit/arm/a64instapi.cpp",
      "//third_party/asmjit/asmjit/arm/a64instdb.cpp",
      "//third_party/asmjit/asmjit/arm/a64operand.cpp",
      "//third_party/asmjit/asmjit/arm/a64rapass.cpp",
      "//third_party/asmjit/asmjit/arm/armformatter.cpp",
      "//third_party/asmjit/asmjit/core/archtraits.cpp",
      "//third_party/asmjit/asmjit/core/assembler.cpp",
      "//third_party/asmjit/asmjit/core/builder.cpp",
      "//third_party/asmjit/asmjit/core/codeholder.cpp",
      "//third_party/asmjit/asmjit/core/codewriter.cpp",
      "//third_party/asmjit/asmjit/core/compiler.cpp",
      "//third_party/asmjit/asmjit/core/constpool.cpp",
      "//third_party/asmjit/asmjit/core/cpuinfo.cpp",
      "//third_party/asmjit/asmjit/core/emithelper.cpp",
      "//third_party/asmjit/asmjit/core/emitter.cpp",
      "//third_party/asmjit/asmjit/core/emitterutils.cpp",
      "//third_party/asmjit/asmjit/core/environment.cpp",
      "//third_party/asmjit/asmjit/core/errorhandler.cpp",
      "//third_party/asmjit/asmjit/core/formatter.cpp",
      "//third_party/asmjit/asmjit/core/func.cpp",
      "//third_party/asmjit/asmjit/core/funcargscontext.cpp",
      "//third_party/asmjit/asmjit/core/globals.cpp",
      "//third_party/asmjit/asmjit/core/inst.cpp",
      "//third_party/asmjit/asmjit/core/instdb.cpp",
      "//third_party/asmjit/asmjit/core/jitallocator.cpp",
      "//third_party/asmjit/asmjit/core/jitruntime.cpp",
      "//third_party/asmjit/asmjit/core/logger.cpp",
      "//third_party/asmjit/asmjit/core/operand.cpp",
      "//third_party/asmjit/asmjit/core/osutils.cpp",
      "//third_party/asmjit/asmjit/core/ralocal.cpp",
      "//third_party/asmjit/asmjit/core/rapass.cpp",
      "//third_party/asmjit/asmjit/core/rastack.cpp",
      "//third_party/asmjit/asmjit/core/string.cpp",
      "//third_party/asmjit/asmjit/core/target.cpp",
      "//third_party/asmjit/asmjit/core/type.cpp",
      "//third_party/asmjit/asmjit/core/virtmem.cpp",
      "//third_party/asmjit/asmjit/support/arena.cpp",
      "//third_party/asmjit/asmjit/support/arenabitset.cpp",
      "//third_party/asmjit/asmjit/support/arenahash.cpp",
      "//third_party/asmjit/asmjit/support/arenalist.cpp",
      "//third_party/asmjit/asmjit/support/arenatree.cpp",
      "//third_party/asmjit/asmjit/support/arenavector.cpp",
      "//third_party/asmjit/asmjit/support/support.cpp",
      "//third_party/asmjit/asmjit/x86/x86assembler.cpp",
      "//third_party/asmjit/asmjit/x86/x86builder.cpp",
      "//third_party/asmjit/asmjit/x86/x86compiler.cpp",
      "//third_party/asmjit/asmjit/x86/x86emithelper.cpp",
      "//third_party/asmjit/asmjit/x86/x86formatter.cpp",
      "//third_party/asmjit/asmjit/x86/x86func.cpp",
      "//third_party/asmjit/asmjit/x86/x86instapi.cpp",
      "//third_party/asmjit/asmjit/x86/x86instdb.cpp",
      "//third_party/asmjit/asmjit/x86/x86operand.cpp",
      "//third_party/asmjit/asmjit/x86/x86rapass.cpp",
    ]
  }
}

lynx_core_source_set("css") {
  check_includes = false

  sources = lynx_css_core_sources_path + lynx_css_runtime_sources_path

  exec_script("../../../tools/css_generator/css_parser_generator.py")

  exec_script("../../../tools/css_generator/generate_layout_property.py",
              [
                rebase_path("../../../tools/css_generator/css_defines"),
                rebase_path("./layout_property.h"),
                rebase_path(
                    "../../../tools/css_generator/css_defines_sha256.txt"),
              ],
              "list lines")

  public_deps = [
    "../../../third_party/rapidjson",
    "../../base",
    "../../runtime/vm/lepus",
    "../../style",
    "../trace:renderer_trace",
  ]

  deps = [
    "../../renderer/dom:dom_headers",
    "../../renderer/starlight:starlight",
  ]

  if (enable_unittests) {
    public_deps += [
      ":css_parser",
      "../../../third_party/double-conversion:double_conversion",
    ]
  }

  if (enable_cssjit) {
    sources += [
      "ng/cssjit_background.cc",
      "ng/cssjit_compiler.cc",
      "ng/cssjit_compiler.h",
      "ng/cssjit_masm.h",
    ]
    deps += [ ":asmjit" ]
  }
}

lynx_core_source_set("css_dom") {
  sources = lynx_css_dom_sources_path
  deps = [ "../../../base/src:base_log_headers" ]
}

lynx_core_source_set("css_decoder") {
  sources = lynx_css_decoder_sources_path
  deps = [ "../../../base/src:base_log_headers" ]
}

lynx_core_source_set("css_parser") {
  sources = lynx_css_parser_sources_path
}

unittest_set("css_test_testset") {
  check_includes = false
  testonly = true
  public_deps = [ ":css" ]

  deps = [
    "../:tasm",
    "../../../third_party/rapidjson:rapidjson",
    "../../renderer:tasm_group",
    "../../runtime/bindings/lepus",
    "../../shell/testing:mock_tasm_delegate_testset",
    "../dom:renderer_dom",
  ]

  sources = [
    "../dom/style_resolver_unittest.cc",
    "computed_css_style_css_text_helper_unittest.cc",
    "css_color_unittest.cc",
    "css_font_face_token_unittest.cc",
    "css_fragment_unittest.cc",
    "css_keyframes_token_unittest.cc",
    "css_keywords_unittest.cc",
    "css_parser_token_unittest.cc",
    "css_property_auto_gen_unittest.cc",
    "css_property_bitset_unittest.cc",
    "css_property_unittest.cc",
    "css_style_sheet_manager_unittest.cc",
    "css_style_utils_unittest.cc",
    "css_utils_unittest.cc",
    "css_value_unittest.cc",
    "css_variable_handler_unittest.cc",
    "shared_css_fragment_unittest.cc",
    "transforms/quaternion_unittest.cc",
    "transforms/transform_operation_unittest.cc",
    "transforms/transform_operations_unittest.cc",
    "unit_handler_unittest.cc",
  ]
}

unittest_set("css_ng_testset") {
  public_deps = [ ":css" ]

  deps = [
    "../:tasm",
    "../../runtime/bindings/lepus",
    "../../shell/testing:mock_tasm_delegate_testset",
    "../dom:renderer_dom",
  ]

  sources = [
    "ng/invalidation/invalidation_set_test.cc",
    "ng/invalidation/rule_invalidation_set_test.cc",
    "ng/matcher/selector_matcher_test.cc",
    "ng/parser/css_parser_token_stream_test.cc",
    "ng/parser/css_tokenizer_test.cc",
    "ng/selector/css_selector_parser_test.cc",
    "ng/selector/lynx_css_selector_test.cc",
    "ng/style/rule_set_unittest.cc",
  ]
}

unittest_exec("css_test_exec") {
  testonly = true
  sources = []
  deps = [
    ":css_ng_testset",
    ":css_test_testset",
    "../dom:dom",
  ]
}

group("css_tests") {
  testonly = true
  deps = [
    ":css_test_exec",
    "parser:css_parser_test_exec",
  ]
  public_deps = [
    ":css_ng_testset",
    ":css_test_testset",
    "parser:css_parser_testset",
  ]
}
